import CriptosContainer from '@/components/CriptosContainer/CriptosContainer'
import Header from '@/components/Header/Header'
import axios from 'axios'
import Head from 'next/head'
import { useEffect, useState } from 'react'

export default function Home() {
  const [criptos, setCriptos] = useState([])
  const [loading, setLoading] = useState(false)
  const API_URL = "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=100&page=1&sparkline=false"

  useEffect(() => {
    setLoading(true);
    axios.get(API_URL)
      .then(data => setCriptos(data.data))
      .catch((e) => console.log(e))
      .finally(() => setLoading(false))
  }, [])

  if (loading) {
    return (
      <p>Cargando...</p>
    )
  }

  return (
    <>
      <Head>
        <title>Criptos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CriptosContainer criptos={criptos} />
    </>
  )
}
